version: '3.7'

services:
  django_gunicorn:
    container_name: django-gunicorn
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    expose:
      - 8000
    

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./letsencrypt:/etc/letsencrypt
      - ./web/static:/code/static
      - ./web/media:/code/media
    depends_on:
      - django_gunicorn

  certbot:
    image: certbot/certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./web/static:/code/static
      - ./web/media:/code/media
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  static:
