version: '3.8'

services:
  web:
    volumes:
      - .:/code
    env_file:
      - .env
    build:
      context: .
    expose:
      - 8000
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - web
      - certbot

  certbot:
      image: certbot/certbot
      volumes:
        - ./letsencrypt:/etc/letsencrypt
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
