version: '3'
services:
  web:
    build:
      context: .
    volumes:
      - .:/app
    env_file:
      - .env
    expose:
      - "8000"  
    ports:
      - "8000:8000"  
      - "8001:8000"  
      - "8002:8000"  
      - "8003:8000"  
      - "8004:8000"  
    deploy:
      replicas: 5   
    restart: always
