version: '3.7'

services:
  django_gunicorn:
    container_name: django-gunicorn
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    expose:
      - 8000
    

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - /home/ubuntu/college-package/nginx:/etc/nginx/conf.d

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email sriramrajaclg@gmail.com -d neuraa.cloudplusai.tech --agree-tos

volumes:
  static:
